variables:
  GIT_SUBMODULE_STRATEGY: recursive
  SECURE_LOG_LEVEL: debug

include:
  - template: Jobs/Secret-Detection.gitlab-ci.yml
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/SAST.gitlab-ci.yml


secret_detection:
  variables:
    GIT_DEPTH: 100

