run-name: 'Build an image and push to Yandex Container Registry'
on:
  push:
    branches:
      - main
      - github-actions-docker-build
jobs:
  build_and_push:
    name: 'Build and push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Yandex CR Login
      uses: yc-actions/yc-cr-login@v3.0.2
      with: 
        yc-sa-json-credentials: ${{secrets.YCR_CREDS_JSON}}
    - name: Build 
      run: |
        cd whoami
        docker build -t cr.yandex/${{secrets.YCR_REGISTRY}}/${{secrets.YCR_REPO}}:${{github.sha}} .
        echo 'IMAGE TAG: ${{github.sha}}'
    - name: scan image with trivy
      run: |
        if ! trivy version &> /dev/null; then
          set -e -o pipefail
          curl -sSL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin > /dev/null
        fi
        trivy image cr.yandex/${{secrets.YCR_REGISTRY}}/${{secrets.YCR_REPO}}:${{github.sha}} --exit-code 0 --format table
    - name: Push
      run: |
        docker push cr.yandex/${{secrets.YCR_REGISTRY}}/${{secrets.YCR_REPO}}:${{github.sha}}
        echo 'IMAGE TAG: ${{github.sha}}'
