on:
  push:
  workflow_dispatch:
    inputs:
      run_manual_steps:
        description: 'Run manual steps?'
        required: false
        type: choice
        options:
        - yes
        - no

name: "Push"
permissions: {}

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: ShellCheck
        if: ${{ inputs.run_manual_steps == 'yes' }}
        uses: ludeeus/action-shellcheck@master
  SemGrep:
    name: SemGrep
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: getsentry/action-setup-venv@v3.0.0
        id: venv
        with:
          # starting from action-setup-venv@v3.0.0, if python-version isn't specified,
          # we default to using the version in .python-version file.
          python-version: 3.11.6
          cache-dependency-path: |
            requirements.txt
            requirements-frozen.txt
      - name: Install Semgrep
        run: |
          if ! python -c 'import semgrep' &> /dev/null; then
            set -e -o pipefail
            pip install semgrep --quiet > /dev/null
          fi
        shell: bash
  
      - name: Run Semgrep SAST
        run: semgrep scan --config auto . || echo "Semgrep exited with non-zero code"
        shell: bash
  
      - name: Install Terrascan
        run: |
          if ! command -v terrascan &> /dev/null; then
           set -e -o pipefail
           curl -sL "$(curl -s https://api.github.com/repos/tenable/terrascan/releases/latest | grep -o -E "https://.+?_Linux_x86_64.tar.gz")" > terrascan.tar.gz
           tar -xf terrascan.tar.gz terrascan > /dev/null 2>&1
           sudo install terrascan /usr/local/bin > /dev/null 2>&1
           rm terrascan terrascan.tar.gz
          fi
        shell: bash
  
      - name: Run terrascan IaC Scan
        run: terrascan scan . || echo "Terrascan exited with non-zero code"
        shell: bash
      
      - name: Install and Run Trivy SCA Scan
        run: |
          if ! trivy version &> /dev/null; then
            set -e -o pipefail
            curl -sSL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin > /dev/null
          fi
          trivy fs --exit-code 0 --format table .
        shell: bash
      - id: govulncheck
        uses: golang/govulncheck-action@v1
